default:
	g++ -o avl avl.cpp -O2
	g++ -o std std.cpp -O2
	g++ -o splay splay.cpp -O2
	g++ -o gen gen.cpp -O2
	g++ -o checker checker.cpp -O2
gen:
	g++ -o gen gen.cpp -O2
checker:
	g++ -o checker checker.cpp -O2
tree:
	g++ -o avl avl.cpp -O2
	g++ -o std std.cpp -O2
	g++ -o splay splay.cpp -O2
clean:
	del avl.exe std.exe splay.exe gen.exe checker.exe